name: debot

services:
  # Frontend Vue.js service
  frontend:
    type: node:18
    port: 5173
    portforward: true  # This allows direct access
    command: cd /app/frontend && yarn dev --host 0.0.0.0
    build:
      - cd /app/frontend && yarn install
    ssl: true
    environment:
      NODE_ENV: development
      LANDO: ON
      # No need for explicit VITE_API_URL as we're using relative URLs now

  # Backend FastAPI service
  backend:
    type: python:3.10
    port: 8000
    portforward: true  # This allows direct access
    command: cd /app/backend && python run.py
    build:
      - cd /app/backend && pip install -r requirements.txt
    ssl: true
    
  # MongoDB service with explicit ARM64 image
  database:
    type: compose
    services:
      image: arm64v8/mongo:4.4
      command: ["mongod", "--bind_ip_all"]
      ports:
        - "27017:27017"

proxy:
  frontend:
    - frontend.debot.lndo.site
    - debot.lndo.site
  
  backend:
    - api.debot.lndo.site
    - api-debot.lndo.site

tooling:
  npm:
    service: frontend
    description: Run npm commands in the frontend service
  yarn:
    service: frontend
    description: Run yarn commands in the frontend service
  python:
    service: backend
  pip:
    service: backend
  mongo:
    service: database 